/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.59
 * Generated at: 2022-08-21 06:49:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class myinfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/views/member/../include/head.jsp", Long.valueOf(1660889923490L));
    _jspx_dependants.put("/WEB-INF/views/member/../include/header.jsp", Long.valueOf(1660896532618L));
    _jspx_dependants.put("jar:file:/D:/Project_Spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/project/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1655882683439L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\r\n");
      out.write("<meta name=\"description\" content=\"\" />\r\n");
      out.write("<meta name=\"author\" content=\"\" />\r\n");
      out.write("<title>Bteam 프로젝트</title>\r\n");
      out.write("\r\n");
      out.write("<!-- 표, 페이징 관련 스타일 -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css\"\r\n");
      out.write("	rel=\"stylesheet\" />\r\n");
      out.write("	\r\n");
      out.write("<!-- 전체 스타일 -->	\r\n");
      out.write("<link href=\"css/styles.css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("<!--  폰트어썸(아이콘) -->\r\n");
      out.write("<script src=\"https://use.fontawesome.com/releases/v6.1.0/js/all.js\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("	\r\n");
      out.write("<!--  폰트어썸 스타일 -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- 달력UI : datepicker 관련된 부분 -->	\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css\">\r\n");
      out.write("  <script src=\"https://code.jquery.com/jquery-3.6.0.js\"></script>\r\n");
      out.write("  <script src=\"https://code.jquery.com/ui/1.13.2/jquery-ui.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("<!-- 부트스트랩 아이콘 -->  \r\n");
      out.write(" <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css\">\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("<!-- 포스트잇 효과 -->	\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Nanum+Pen+Script&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- 엑셀변환 라이브러리 -->\r\n");
      out.write("<script src=\"js/xlsx.core.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"js/FileSaver.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"js/tableexport.js\"></script>\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("</head>");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("h3{\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	margin: 10px auto\r\n");
      out.write("}\r\n");
      out.write(".content{ \r\n");
      out.write("	width: 480px;\r\n");
      out.write("    height: 500px;\r\n");
      out.write("    background: #e9e9e9;\r\n");
      out.write("    border-radius: 20px;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    flex-direction: column;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("  	left:50%; top:50%;\r\n");
      out.write("	transform:translate(-50%, -50%);\r\n");
      out.write(" 	opacity: 0.9;\r\n");
      out.write("}\r\n");
      out.write(".info {\r\n");
      out.write("	margin: 40px 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input {\r\n");
      out.write("	width: 280px;\r\n");
      out.write("    height: 30px;\r\n");
      out.write("    padding: 0 10px;\r\n");
      out.write("    font-size: 15px;\r\n");
      out.write("    border: 1px solid #AB92BF;\r\n");
      out.write("    margin: 10px auto;\r\n");
      out.write("}\r\n");
      out.write("a.btn-empty {\r\n");
      out.write("	background-color: #fff;\r\n");
      out.write("	color:#3367d6;	\r\n");
      out.write("}\r\n");
      out.write(".btnSet { margin-top:30px; margin-bottom:30px; }\r\n");
      out.write("</style>\r\n");
      out.write("<body class=\"sb-nav-fixed\">\r\n");
      out.write("\r\n");
      out.write("	<!-- 여기가 헤더부분 -->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("	<!--  헤더 부분  -->\r\n");
      out.write("	<nav class=\"sb-topnav navbar navbar-expand navbar-dark bg-sclass\">\r\n");
      out.write("		<!-- Navbar Brand-->\r\n");
      out.write("		<button class=\"btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0\"	id=\"sidebarToggle\" href=\"#!\">\r\n");
      out.write("			<i class=\"fs-5 fas fa-bars\"></i>\r\n");
      out.write("		</button>\r\n");
      out.write("		<a class=\"navbar-brand ps-3\" href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\"><img src='img/logo04.png' width='160px' height='50px'></a>\r\n");
      out.write("		<p class=\"text-white fs-5 hong_vam\"> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginInfo.teacher_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("님 어서오세요</p>\r\n");
      out.write("		<!-- Sidebar Toggle-->\r\n");
      out.write("		<!-- Navbar Search-->\r\n");
      out.write("		<form\r\n");
      out.write("			class=\"d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0\">\r\n");
      out.write("			<div class=\"input-group\">\r\n");
      out.write("				\r\n");
      out.write("			</div>\r\n");
      out.write("		</form>\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		<!-- Navbar-->\r\n");
      out.write("		<ul class=\"navbar-nav ms-auto ms-md-0 me-3 me-lg-4\">\r\n");
      out.write("			");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("			<li class=\"nav-item\">\r\n");
      out.write("				<a class=\"nav-link darkmode\">\r\n");
      out.write("					<i class=\"fs-5 fas fa-moon\"></i></a>\r\n");
      out.write("			</li>\r\n");
      out.write("			<li class=\"nav-item dropdown\">\r\n");
      out.write("				<a class=\"nav-link dropdown-toggle\" id=\"navbarDropdown\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("					<i class=\"fs-5 fas fa-user fa-fw\"></i></a>\r\n");
      out.write("				<ul class=\"dropdown-menu dropdown-menu-end\"\r\n");
      out.write("					aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("					<li><a class=\"dropdown-item\" href=\"myinfo\">마이페이지</a></li>\r\n");
      out.write("					<li><hr class=\"dropdown-divider\" /></li>\r\n");
      out.write("					<li><a class=\"dropdown-item\" href=\"logout\">로그아웃</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</nav>\r\n");
      out.write("	<!-- 여기까지가 헤더부분 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<h2>정보 수정페이지</h2>\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"content\">\r\n");
      out.write("		<div class=\"info\">\r\n");
      out.write("		<h3>내 정보/수정</h3>\r\n");
      out.write("		<form action=\"changeInfo\" method=\"post\">\r\n");
      out.write("			아이디<br><input type=\"text\" name=\"teacher_id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.teacher_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly><br/>\r\n");
      out.write("			비밀번호 변경<br><input type=\"text\" name=\"pw\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.teacher_pw}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" ><br/>\r\n");
      out.write("			이름<br><input type=\"text\" name=\"teacher_name\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.teacher_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"><br/>\r\n");
      out.write("			이메일<br><input type=\"text\" name=\"email\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"><br/>\r\n");
      out.write("			전화번호<br><input type=\"text\" name=\"teacher_phone\" maxlength=\"13\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.teacher_phone}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("			<br>		\r\n");
      out.write("			<button type='submit'>수정</button>\r\n");
      out.write("		\r\n");
      out.write("			<a class='btn-empty' onclick='history.go(-1)'>취소</a>\r\n");
      out.write("		\r\n");
      out.write("		</form>\r\n");
      out.write("		</div>	\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--  여기까지 콘텐트 + 푸터 부분 -->\r\n");
      out.write("\r\n");
      out.write("<!-- 부트스트랩 js -->\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- 템플릿 js -->\r\n");
      out.write("<script src=\"js/scripts.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"/js/demo/chart-area-demo.js\"></script>\r\n");
      out.write("<script src=\"/js/demo/chart-bar-demo.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- 표 / 페이징 관련 js -->\r\n");
      out.write("<script src=\"js/simple-datatables.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"js/datatables-simple-demo.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("		\r\n");
      out.write("	 // 다크모드 버튼 (흰배경+검정배경)\r\n");
      out.write("	 let $darkModeBtn = document.querySelector('.darkmode');\r\n");
      out.write("	 let bgsclass = document.querySelector('.bg-sclass');\r\n");
      out.write("	 let body = document.querySelector('body');\r\n");
      out.write("	 let content = document.querySelector('.content');\r\n");
      out.write("	 let dark = 'on'; //불값을 저장하여 온오프기능 구현	\r\n");
      out.write("	 let play = false;\r\n");
      out.write("	 if(window.localStorage.getItem(\"darkmode\") != null){\r\n");
      out.write("		 dark = window.localStorage.getItem(\"darkmode\");\r\n");
      out.write("	 }  \r\n");
      out.write("	 \r\n");
      out.write("	 \r\n");
      out.write("	  if( dark == 'off' ){\r\n");
      out.write("	        \r\n");
      out.write("          body.setAttribute('style', 'background:#3d3d3d');\r\n");
      out.write("          content.setAttribute('style', 'background:#767676');\r\n");
      out.write("          bgsclass.setAttribute('class', 'sb-topnav navbar navbar-expand navbar-dark bg-dark');\r\n");
      out.write("        } else {\r\n");
      out.write("          body.setAttribute('style', 'background:#fafafa');\r\n");
      out.write("          content.setAttribute('style', 'background:#e9e9e9');\r\n");
      out.write("          bgsclass.setAttribute('class', 'sb-topnav navbar navbar-expand navbar-dark bg-sclass');\r\n");
      out.write("        }\r\n");
      out.write("       \r\n");
      out.write("		// 다크모드\r\n");
      out.write("	    $darkModeBtn.addEventListener('click', () => {\r\n");
      out.write("	    	if(dark == 'on'){\r\n");
      out.write("	    		dark='off';\r\n");
      out.write("	    	}else{\r\n");
      out.write("	    		dark = 'on';\r\n");
      out.write("	    	}\r\n");
      out.write("	    	\r\n");
      out.write("	      	window.localStorage.setItem(\"darkmode\",dark);\r\n");
      out.write("			\r\n");
      out.write("\r\n");
      out.write("	        if( dark == 'off' ){\r\n");
      out.write("	        	body.setAttribute('style', 'background:#3d3d3d');\r\n");
      out.write("	        	content.setAttribute('style', 'background:#767676');\r\n");
      out.write("	          bgsclass.setAttribute('class', 'sb-topnav navbar navbar-expand navbar-dark bg-dark');\r\n");
      out.write("	        } else {\r\n");
      out.write("	          body.setAttribute('style', 'background:#fafafa');\r\n");
      out.write("	          content.setAttribute('style', 'background:#e9e9e9');\r\n");
      out.write("	          bgsclass.setAttribute('class', 'sb-topnav navbar navbar-expand navbar-dark bg-sclass');\r\n");
      out.write("	        }\r\n");
      out.write("	      });\r\n");
      out.write("	\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/views/member/../include/header.jsp(12,37) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/main");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/member/../include/header.jsp(28,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${teacher_id eq 'admin'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				<li class=\"nav-item\">\r\n");
          out.write("					<a class=\"nav-link playmode\">\r\n");
          out.write("						<i class=\"fa-solid fa-play\"></i>\r\n");
          out.write("					</a>\r\n");
          out.write("				</li>\r\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
